id: IE6C6D5C9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T23:37:02+00:00'
last_modified: '2022-06-08T11:47:29.616072+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17931
  title: མངོན་པ་མཛོད་ཀྱི་དགོངས་འགྲེལ་བསྟན་བཅོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    77C6:
      image_group_id: I8LS17940
      title: ''
      total_pages: 1356
      order: 1
      base_file: 77C6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
